### ISSUE TITLE
Install failed: error notion-enhancer@0.10.1 postinstall: `node bin.js apply -y`

### ISSUE THREAD

**Issue by Benature** [notion-enhancer/notion-enhancer#301]
**describe the bug**
update failed and I cannot find notion-enhancer anymore. So I uninstall it and reinstall, then failed again

```shell
(base)  ~  sudo chmod -R a+wr /usr/local/lib/node_modules
sudo chmod -R a+wr /usr/local/bin
sudo chmod -R a+wr /Applications/Notion.app/Contents/Resources
(base)  ~  npm i -g notion-enhancer

> notion-enhancer@0.10.1 preuninstall /usr/local/lib/node_modules/notion-enhancer
> node bin.js remove -n

=== NOTION RESTORATION LOG ===
 ...removing folder /Applications/Notion.app/Contents/Resources/app
 * /Applications/Notion.app/Contents/Resources/app.asar.bak not found: step skipped.
 ...data folder /Users/benature/.notion-enhancer found.
 > delete? [Y/n]: n
 -- keeping /Users/benature/.notion-enhancer
 ~~ success.
=== END OF LOG ===
/usr/local/bin/notion-enhancer -> /usr/local/lib/node_modules/notion-enhancer/bin.js

> notion-enhancer@0.10.1 postinstall /usr/local/lib/node_modules/notion-enhancer
> node bin.js apply -y

/usr/local/lib/node_modules/notion-enhancer/pkg/helpers.js:90
        throw new EnhancerError(
        ^

EnhancerError: nothing found: notion installation is either corrupted or non-existent.
    at /usr/local/lib/node_modules/notion-enhancer/pkg/helpers.js:90:15
    at Object.<anonymous> (/usr/local/lib/node_modules/notion-enhancer/pkg/helpers.js:95:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/notion-enhancer/bin.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:959:30) {
  name: 'EnhancerError'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notion-enhancer@0.10.1 postinstall: `node bin.js apply -y`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the notion-enhancer@0.10.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benature/.npm/_logs/2020-12-02T08_13_52_667Z-debug.log
```

**platform**
macOS 10.15.7

**Comment by alyssasmith0328** [comment]
I'm getting the exact same thing.

**Comment by dragonwocky** [comment]
#300
