### ISSUE TITLE
Unable to install  notion-enhancer on Mac Big Sur

### ISSUE THREAD

**Issue by nandudb** [notion-enhancer/notion-enhancer#450]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
When i run `npm i -g notion-enhancer`, i get the following error on Mac Big Sur 11.2.3

```
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/notion-enhancer/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
npm WARN notsup Unsupported engine for asar@3.0.3: wanted: {"node":">=10.12.0"} (current: {"node":"8.9.1","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: asar@3.0.3
npm WARN notsup Unsupported engine for fs-extra@9.1.0: wanted: {"node":">=10"} (current: {"node":"8.9.1","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: fs-extra@9.1.0
npm WARN notsup Unsupported engine for readdir-enhanced@6.0.4: wanted: {"node":">=10"} (current: {"node":"8.9.1","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: readdir-enhanced@6.0.4
npm WARN notsup Unsupported engine for universalify@2.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.9.1","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: universalify@2.0.0
npm WARN notsup Unsupported engine for @jsdevtools/readdir-enhanced@6.0.4: wanted: {"node":">=10"} (current: {"node":"8.9.1","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: @jsdevtools/readdir-enhanced@6.0.4
npm WARN notsup Unsupported engine for @jsdevtools/file-path-filter@3.0.2: wanted: {"node":">=10"} (current: {"node":"8.9.1","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: @jsdevtools/file-path-filter@3.0.2

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notion-enhancer@0.10.2 postinstall: `node bin.js apply -y`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the notion-enhancer@0.10.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

**Comment by dragonwocky** [comment]
you're using an outdated version of Node (8.9.1). upgrading to the latest LTS (14.16.0) should fix this.

**Comment by nandudb** [comment]
Thanks. It did fix the issue
