### ISSUE TITLE
Terminal error attempting install

### ISSUE THREAD

**Issue by madalenaacgl** [notion-enhancer/notion-enhancer#551]
**describe the bug**
Get the following error message when trying to enter the installation lines on Terminal:

Error: Cannot copy '../shared/notion-intl' to a subdirectory of itself, '../shared/notion-intl'.
    at /usr/local/lib/node_modules/notion-enhancer/node_modules/fs-extra/lib/copy/copy.js:210:21
    at FSReqCallback.oncomplete (fs.js:180:23)
=== END OF LOG ===

**expected behaviour**
Should be able to install/run Notion Enhancer.

**platform**
macOS

**note**
I have checked for previous threads describing this issue/potential fixes for it, and as far as I can tell I have done everything right, e.g. can confirm I have the latest version of Notion installed. Apologies if there's another fix out there I haven't found -- really appreciate your willingness to help users!

**Comment by dragonwocky** [comment]
this happens sometimes without much reason. you'll probably have an easier time installing the .dmg from https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-1 (uninstall normal notion first tho).
