### ISSUE TITLE
Notion Enhancer crashes on startup (Ubuntu)

### ISSUE THREAD

**Issue by m-schmale** [notion-enhancer/notion-enhancer#577]
Hi :)

Could you please help me with this issue?

**describe the bug**

When I installed the app today it was working, but I had this bug: https://github.com/notion-enhancer/notion-enhancer/issues/291 Now, Notion Enhancer crashes with these errors on startup:

`"/opt/Notion Enhanced/notion-app-enhanced"
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
17:08:56.894 › Checking for update
(node:221052) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
17:08:57.324 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/mark/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
17:08:57.331 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'
17:08:57.342 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: { version: '23.9.3.0' }
}
17:08:57.344 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersions',
  data: {
    message: 'Sync versions: assets.json path /home/mark/.config/notion-app-enhanced/notionAssetCache-v2/23.9.3.0/assets.json headers.json path /home/mark/.config/notion-app-enhanced/notionAssetCache-v2/23.9.3.0/headers.json'
  }
}
17:08:57.359 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: { version: '23.9.3.0' }
}
17:08:57.390 › {
  level: 'error',
  from: 'main',
  type: 'unhandledRejection',
  error: {
    name: 'TypeError',
    message: 'focused_window.isMaximized is not a function',
    stack: 'TypeError: focused_window.isMaximized is not a function\n' +
      '    at Object.__exports.createWindow (/opt/Notion Enhanced/resources/app/embedded_enhancer/mods/core/createWindow.js:42:43)\n' +
      '    at handleActivate (/opt/Notion Enhanced/resources/app/main/main.js:71:36)\n' +
      '    at startup (/opt/Notion Enhanced/resources/app/main/main.js:149:5)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
  }
}
17:08:57.754 › Websocket listening on 33823...
17:08:57.761 › Set up server listeners with auth (cb55616a8a226674405a1b68502451ba4000ca9b)...`

**expected behaviour**
It should open properly.

**screenshots**
Not necessary.

**platform**
Ubuntu 20.04.3 LTS 64-bit

Thanks,
Mark

**Comment by m-schmale** [comment]
I've killed the process and now it's working again. But I don't know if this "solution" is permanent.

**Comment by dragonwocky** [comment]
did you install with notion-repackaged or from npm?

**Comment by m-schmale** [comment]
> did you install with notion-repackaged or from npm?

notion-repackaged

**Comment by Johoyos** [comment]
I still have that issue when I installed from yay(aur). Do you have the code from app-update.yml? 

[yoncho@myarch ~]$ notion-app-enhanced
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
00:31:47.249 › Checking for update
(node:41552) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
00:31:47.860 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/yoncho/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
00:31:47.870 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'
00:31:47.895 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: { version: '23.9.6.0' }
}
00:31:47.898 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersions',
  data: {
    message: 'Sync versions: assets.json path /home/yoncho/.config/notion-app-enhanced/notionAssetCache-v2/23.9.6.0/assets.json headers.json path /home/yoncho/.config/notion-app-enhanced/notionAssetCache-v2/23.9.6.0/headers.json'
  }
}
00:31:47.919 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: { version: '23.9.6.0' }
}

**Comment by m-schmale** [comment]
@Johoyos

I created a file with this content (no idea, if this is correct):

```
provider: generic
url: 'https://desktop-release.notion-static.com/'
channel: latest
```

And now this error is gone. But Notion Enhancer still crashes because of this error:

```
12:50:28.694 › {
  level: 'error',
  from: 'main',
  type: 'unhandledRejection',
  error: {
    name: 'TypeError',
    message: 'focused_window.isMaximized is not a function',
    stack: 'TypeError: focused_window.isMaximized is not a function\n' +
      '    at Object.__exports.createWindow (/opt/Notion Enhanced/resources/app/embedded_enhancer/mods/core/createWindow.js:42:43)\n' +
      '    at handleActivate (/opt/Notion Enhanced/resources/app/main/main.js:71:36)\n' +
      '    at startup (/opt/Notion Enhanced/resources/app/main/main.js:149:5)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
  }
}
```

**Comment by Johoyos** [comment]
Thanks. 
I'm in arch linux and I still got this and doesn't open :
```
[yoncho@myarch ~]$ notion-app-enhanced
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
10:55:27.927 › Checking for update
(node:100192) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
10:55:28.573 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/yoncho/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
10:55:28.620 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: { version: '23.9.6.0' }
}
10:55:28.622 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersions',
  data: {
    message: 'Sync versions: assets.json path /home/yoncho/.config/notion-app-enhanced/notionAssetCache-v2/23.9.6.0/assets.json headers.json path /home/yoncho/.config/notion-app-enhanced/notionAssetCache-v2/23.9.6.0/headers.json'
  }
}
10:55:28.631 › Generated new staging user ID: 87a4e891-e926-5efd-ae3a-ffe0b78cec0a

```

**Comment by Johoyos** [comment]
Hi, I solved it with help of Jamezrin. He told me this: 
run these commands: 
`killall notion-app-enhanced`
`rm -r ~/.config/notion-app-enhanced ~/.notion-enhancer`
then install the latest version
And it worked. I can open notion-app-enhanced

**Comment by m-schmale** [comment]
@Johoyos @jamezrin 

Thanks, but unfortunately, this fix does not work for me. However, the top bar is not bugged anymore, and I can still use the workaround (kill the app first) to start the app.

**Log**
```
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
22:51:58.748 › Checking for update
(node:345525) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
22:51:59.181 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/mark/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
22:51:59.189 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'
22:51:59.191 › {
  level: 'info',
  from: 'AssetCache',
  type: 'errorReadingPath',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/home/mark/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'",
    stack: "Error: ENOENT: no such file or directory, open '/home/mark/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'"
  },
  data: {
    message: 'Error reading /home/mark/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
22:51:59.192 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: {}
}
22:51:59.193 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersionEmptyLatestVersion'
}
22:51:59.194 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: {}
}
22:51:59.222 › {
  level: 'error',
  from: 'main',
  type: 'unhandledRejection',
  error: {
    name: 'TypeError',
    message: 'focused_window.isMaximized is not a function',
    stack: 'TypeError: focused_window.isMaximized is not a function\n' +
      '    at Object.__exports.createWindow (/opt/Notion Enhanced/resources/app/embedded_enhancer/mods/core/createWindow.js:42:43)\n' +
      '    at handleActivate (/opt/Notion Enhanced/resources/app/main/main.js:71:36)\n' +
      '    at startup (/opt/Notion Enhanced/resources/app/main/main.js:149:5)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
  }
}
```

**Comment by ATahma** [comment]
I've been running into a similar issue which [according to AUR](https://aur.archlinux.org/packages/notion-app-enhanced) is due to a new notion update. In the meantime, I have been using **CTRL + ALT + E** to access the enhancer.
